version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: selenium/standalone-chrome:3.1.0
    environment:
      - FOO: "testing"
    working_directory: ~/testCI
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm test
      - run: echo $FOO

      # save errorShots
      - store_artifacts:
          path: ./errorShots/
          when: always
          destination: prefix

      # save the xml file to reports
      - store_artifacts:
          path: ./reports/
          when: always
          destination: prefix

      # save the build results
      - store_test_results:
          path: ./reports/

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "hello world"
   
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
